import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { Suspense } from "react";
import Navbar from "@/components/layout/Navbar";
import { PiProvider } from "@/context/PiContext";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import AIAssistant from '@/components/ui/AIAssistant';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <Script
          src="https://sdk.minepi.com/pi-sdk.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className="min-h-full flex flex-col bg-black">
        <AuthProvider>
          <PiProvider>
            <Suspense fallback={<div className="h-20 sm:h-24 bg-gray-900" />}>
              <Navbar />
            </Suspense>
            <main className="pt-16 sm:pt-20">
              {children}
            </main>
            <Suspense fallback={null}>
              <AIAssistant />
            </Suspense>
          </PiProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
